version: '3.8'
services:
  el:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    depends_on:
      - el
    environment:
      ELASTICSEARCH_HOSTS: http://el:9200
    ports:
      - 5601:5601
    networks:
      - elk
      
  application:
    build: ./application
    depends_on:
      - kibana
    ports:
      - 8080:80
    networks:
      - elk

networks:
  elk:
    driver: bridge